/* Task 1 candidate activity stimuli (N = 90) — from the team doc
   "Task 1 Candidate Activity Stimuli (N = 90) — v2", verbatim. Rated in
   ratings/index.html on two 0–100 scales (enjoyable now / useful for the
   quiz). `flagged` = item carried an asterisk in the doc (pending review).
   The list itself is pending Karine's review. */

const ACTIVITIES = [
  // 1. Study activities (goal)
  { id: 's1', cat: 'study', en: 'Practice explaining the material to someone else', pt: 'Explicar a matéria para alguém', flagged: true },
  { id: 's2', cat: 'study', en: 'Teach the material to a friend', pt: 'Ensinar a matéria para um amigo', flagged: true },
  { id: 's3', cat: 'study', en: 'Work through a difficult problem step by step', pt: 'Resolver uma questão difícil passo a passo' },
  { id: 's4', cat: 'study', en: 'Practice questions without looking at your notes', pt: 'Fazer questões sem consultar as anotações' },
  { id: 's5', cat: 'study', en: 'Write down everything you remember about the topic', pt: 'Escrever tudo o que você lembra sobre a matéria' },
  { id: 's6', cat: 'study', en: 'Make a list of questions you still have', pt: 'Fazer uma lista das dúvidas que ainda tem' },
  { id: 's7', cat: 'study', en: 'Look up an explanation of something you don\'t understand', pt: 'Procurar uma explicação para algo que você não entendeu' },
  { id: 's8', cat: 'study', en: 'Ask a classmate for help with the material', pt: 'Pedir ajuda a um colega com a matéria', flagged: true },
  { id: 's9', cat: 'study', en: 'Study with a classmate', pt: 'Estudar com um colega', flagged: true },
  { id: 's10', cat: 'study', en: 'Make a study plan for the quiz', pt: 'Fazer um plano de estudos para a prova' },
  { id: 's11', cat: 'study', en: 'Set a study goal for the next 30 minutes', pt: 'Definir uma meta de estudo para os próximos 30 minutos' },
  { id: 's12', cat: 'study', en: 'Practice the questions you got wrong before', pt: 'Praticar as questões que você errou antes' },
  { id: 's13', cat: 'study', en: 'Compare your answers with the answer key', pt: 'Comparar suas respostas com o gabarito' },
  { id: 's14', cat: 'study', en: 'Work on a sample test', pt: 'Fazer uma prova de prática' },
  { id: 's15', cat: 'study', en: 'Create questions that could appear on the quiz', pt: 'Criar questões que poderiam aparecer na prova' },
  { id: 's16', cat: 'study', en: 'Use an educational app to practice the material', pt: 'Usar um aplicativo educativo para praticar a matéria' },
  { id: 's17', cat: 'study', en: 'Watch a tutorial about a difficult topic', pt: 'Assistir a um tutorial sobre um assunto difícil' },
  { id: 's18', cat: 'study', en: 'Review the topics you know the least', pt: 'Revisar os assuntos que você menos domina' },
  { id: 's19', cat: 'study', en: 'Practice until you can answer without help', pt: 'Praticar até conseguir responder sem ajuda' },
  { id: 's20', cat: 'study', en: 'Go through the teacher\'s review sheet', pt: 'Revisar o roteiro de revisão do professor' },
  { id: 's21', cat: 'study', en: 'Review your class notes', pt: 'Rever suas anotações da aula' },
  { id: 's22', cat: 'study', en: 'Reread the textbook chapter', pt: 'Reler o capítulo do livro' },
  { id: 's23', cat: 'study', en: 'Make a summary of the material', pt: 'Fazer um resumo da matéria' },
  { id: 's24', cat: 'study', en: 'Study with digital flashcards', pt: 'Estudar com flashcards digitais' },
  { id: 's25', cat: 'study', en: 'Watch a review video lesson', pt: 'Assistir a uma videoaula de revisão' },
  { id: 's26', cat: 'study', en: 'Highlight the key points', pt: 'Grifar os pontos principais' },
  { id: 's27', cat: 'study', en: 'Make a mind map of the topic', pt: 'Fazer um mapa mental da matéria' },
  { id: 's28', cat: 'study', en: 'Memorize the key definitions', pt: 'Decorar as definições principais' },
  { id: 's29', cat: 'study', en: 'Recopy your notes neatly', pt: 'Passar a matéria a limpo' },
  { id: 's30', cat: 'study', en: 'Solve the exercises in the book', pt: 'Resolver os exercícios do livro' },
  // 2. Entertainment activities (temptation)
  { id: 'e1', cat: 'entertainment', en: 'Scroll Instagram Reels', pt: 'Rolar os Reels do Instagram', sub: 'Social media' },
  { id: 'e2', cat: 'entertainment', en: 'Check Instagram Stories', pt: 'Ver os Stories do Instagram', sub: 'Social media' },
  { id: 'e3', cat: 'entertainment', en: 'Look at your friends\' posts', pt: 'Ver as publicações dos seus amigos', sub: 'Social media' },
  { id: 'e4', cat: 'entertainment', en: 'Watch YouTube Shorts', pt: 'Assistir a Shorts no YouTube', sub: 'Short video' },
  { id: 'e5', cat: 'entertainment', en: 'Watch TikTok videos', pt: 'Ver vídeos no TikTok', sub: 'Short video' },
  { id: 'e6', cat: 'entertainment', en: 'Play a match of Free Fire', pt: 'Jogar uma partida de Free Fire', sub: 'Gaming' },
  { id: 'e7', cat: 'entertainment', en: 'Play Minecraft', pt: 'Jogar Minecraft', sub: 'Gaming' },
  { id: 'e8', cat: 'entertainment', en: 'Play console soccer (FIFA)', pt: 'Jogar videogame (FIFA)', sub: 'Gaming' },
  { id: 'e9', cat: 'entertainment', en: 'Watch an episode of your series', pt: 'Assistir a um episódio da série', sub: 'Streaming' },
  { id: 'e10', cat: 'entertainment', en: 'Watch anime', pt: 'Assistir a um anime', sub: 'Streaming' },
  { id: 'e11', cat: 'entertainment', en: 'Watch a streamer\'s live', pt: 'Assistir à live de um streamer', sub: 'Creators' },
  { id: 'e12', cat: 'entertainment', en: 'Watch your YouTuber\'s new video', pt: 'Ver o vídeo novo do seu youtuber', sub: 'Creators' },
  { id: 'e13', cat: 'entertainment', en: 'Watch reaction videos', pt: 'Assistir a vídeos de reação', sub: 'Creators' },
  { id: 'e14', cat: 'entertainment', en: 'Listen to your favorite playlist', pt: 'Ouvir sua playlist favorita', sub: 'Music' },
  { id: 'e15', cat: 'entertainment', en: 'Watch music videos', pt: 'Assistir a clipes de música', sub: 'Music' },
  { id: 'e16', cat: 'entertainment', en: 'Watch soccer highlights', pt: 'Ver lances de futebol', sub: 'Sports content' },
  { id: 'e17', cat: 'entertainment', en: 'Chat in the WhatsApp group', pt: 'Conversar no grupo do WhatsApp', sub: 'Socializing' },
  { id: 'e18', cat: 'entertainment', en: 'Send voice messages to friends', pt: 'Mandar áudios para os amigos', sub: 'Socializing' },
  { id: 'e19', cat: 'entertainment', en: 'Video call a friend', pt: 'Fazer uma chamada de vídeo', sub: 'Socializing' },
  { id: 'e20', cat: 'entertainment', en: 'Go to a friend\'s house', pt: 'Ir à casa de um amigo', sub: 'Socializing' },
  { id: 'e21', cat: 'entertainment', en: 'Go to the mall with friends', pt: 'Ir ao shopping com os amigos', sub: 'Socializing' },
  { id: 'e22', cat: 'entertainment', en: 'Go out to eat with friends', pt: 'Sair para comer com os amigos', sub: 'Food' },
  { id: 'e23', cat: 'entertainment', en: 'Order a snack on iFood', pt: 'Pedir um lanche no iFood', sub: 'Food' },
  { id: 'e24', cat: 'entertainment', en: 'Play soccer outside', pt: 'Jogar bola lá fora', sub: 'Physical' },
  { id: 'e25', cat: 'entertainment', en: 'Play volleyball', pt: 'Jogar vôlei', sub: 'Physical' },
  { id: 'e26', cat: 'entertainment', en: 'Ride a bike', pt: 'Andar de bicicleta', sub: 'Physical' },
  { id: 'e27', cat: 'entertainment', en: 'Go for a swim', pt: 'Ir nadar', sub: 'Physical' },
  { id: 'e28', cat: 'entertainment', en: 'Take a nap', pt: 'Tirar uma soneca', sub: 'Relaxation' },
  { id: 'e29', cat: 'entertainment', en: 'Play a card or board game', pt: 'Jogar um jogo de cartas', sub: 'Relaxation' },
  { id: 'e30', cat: 'entertainment', en: 'Look at clothes/ sneakers online', pt: 'Ver roupas ou tênis online', sub: 'Shopping' },
  // 3. Neutral activities
  { id: 'n1', cat: 'neutral', en: 'Water the plants', pt: 'Regar as plantas' },
  { id: 'n2', cat: 'neutral', en: 'Fold the laundry', pt: 'Dobrar as roupas' },
  { id: 'n3', cat: 'neutral', en: 'Sweep the floor', pt: 'Varrer o chão' },
  { id: 'n4', cat: 'neutral', en: 'Wash the dishes', pt: 'Lavar a louça' },
  { id: 'n5', cat: 'neutral', en: 'Take out the trash', pt: 'Levar o lixo para fora' },
  { id: 'n6', cat: 'neutral', en: 'Make your bed', pt: 'Arrumar a cama' },
  { id: 'n7', cat: 'neutral', en: 'Tidy your desk', pt: 'Arrumar sua mesa' },
  { id: 'n8', cat: 'neutral', en: 'Organize the closet', pt: 'Organizar o guarda-roupa' },
  { id: 'n9', cat: 'neutral', en: 'Match the clean socks', pt: 'Parear as meias limpas' },
  { id: 'n10', cat: 'neutral', en: 'Wipe the kitchen table', pt: 'Limpar a mesa da cozinha' },
  { id: 'n11', cat: 'neutral', en: 'Refill your water bottle', pt: 'Encher sua garrafa de água' },
  { id: 'n12', cat: 'neutral', en: 'Organize the bookshelf', pt: 'Organizar a estante' },
  { id: 'n13', cat: 'neutral', en: 'Hang up the clothes', pt: 'Pendurar as roupas' },
  { id: 'n14', cat: 'neutral', en: 'Put away the dishes', pt: 'Guardar a louça' },
  { id: 'n15', cat: 'neutral', en: 'Dust the shelves', pt: 'Tirar o pó da estante' },
  { id: 'n16', cat: 'neutral', en: 'Sweep the yard', pt: 'Varrer o quintal' },
  { id: 'n17', cat: 'neutral', en: 'Clean your sneakers', pt: 'Limpar seu tênis' },
  { id: 'n18', cat: 'neutral', en: 'Sort the recycling', pt: 'Separar o lixo reciclável' },
  { id: 'n19', cat: 'neutral', en: 'Untangle the cables', pt: 'Desembaraçar os fios' },
  { id: 'n20', cat: 'neutral', en: 'Sharpen your pencils', pt: 'Apontar seus lápis' },
  { id: 'n21', cat: 'neutral', en: 'Buy bread at the bakery', pt: 'Comprar pão na padaria', flagged: true },
  { id: 'n22', cat: 'neutral', en: 'Set the table', pt: 'Pôr a mesa' },
  { id: 'n23', cat: 'neutral', en: 'Feed the pet', pt: 'Dar comida para o pet', flagged: true },
  { id: 'n24', cat: 'neutral', en: 'Organize a kitchen drawer', pt: 'Arrumar a gaveta da cozinha' },
  { id: 'n25', cat: 'neutral', en: 'Clean the mirror', pt: 'Limpar o espelho' },
  { id: 'n26', cat: 'neutral', en: 'Fold the towels', pt: 'Dobrar as toalhas' },
  { id: 'n27', cat: 'neutral', en: 'Clean the fan', pt: 'Limpar o ventilador' },
  { id: 'n28', cat: 'neutral', en: 'Straighten the sofa cushions', pt: 'Ajeitar as almofadas do sofá' },
  { id: 'n29', cat: 'neutral', en: 'Check the mailbox', pt: 'Olhar a caixa de correio' },
  { id: 'n30', cat: 'neutral', en: 'Peel vegetables for dinner', pt: 'Descascar os legumes do jantar' },
];

/* Video preview stimuli for the Task 2 rating block: the current Task 2
   playlist (shared/videos.js), thumbnails from YouTube. Replace with the
   team's candidate list when available. */
const VIDEO_STIMULI = VIDEOS.map(v => ({ id: v.id, cat: v.cat, thumb: 'https://img.youtube.com/vi/' + v.id + '/hqdefault.jpg' }));
